apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapi
  template:
    metadata:
      labels:
        app: crudapi
    spec:
      containers:
        - name: crudapi-container
          image: crudapi:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: crudapi-service
spec:
  type: NodePort
  selector:
    app: crudapi
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
